### ISSUE TITLE
> out | ls et ls | > out

### ISSUE THREAD

**Issue by cha202** [Jauppp/minishell#61]
bash :
$ > out | ls
0  in  includes  Makefile  minishell  misc  out  scripts  src

-> ls fonctionne et out est cree

minishell :
Minishell > > out | ls

-> il ne se passe rien

bash :
$ ls | > out
$ 

-> out est cree

minishell :
Minishell > ls | > out
close_write (pfd[W]): Bad file descriptor
close_read (pfd[R]): Bad file descriptor

-> out n'est pas cree

**Comment by Jauppp** [comment]
fixed by updating logic checking position of command in pipeline
