### ISSUE TITLE
< in | cat et cat | < in

### ISSUE THREAD

**Issue by cha202** [Jauppp/minishell#62]
**bash:**
$ < in | cat
$

-> ne se passe rien

**minishell :**
Minishell > < in | cat
hello
Minishell >

-> cat fonctionne

**bash :**
$ cat | < in
hello
$ 

-> cat fonctionne mais s'arrete des le premier retour a la ligne

**minishell :**
Minishell > cat | <in 
close_write (pfd[W]): Bad file descriptor
close_read (pfd[R]): Bad file descriptor
hello
Minishell >

fait comme bash

**Comment by Jauppp** [comment]
fixed by fixing other issues IG ? it works fine
