### ISSUE TITLE
soucis builtin

### ISSUE THREAD

**Issue by cha202** [Jauppp/minishell#64]
-> les builtins ne se font pas si il y a un pipe :

Minishell > echo $PATH | cat
-- pmin ------------
main
echo [echo] [/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin] pipe command [/usr/bin/cat] 
--------------------
-- execve ----------
Minishell > 

-> builtin se fait deux fois s'il est seul

Minishell > echo $PATH
-- pmin ------------
main
echo [echo] [/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin] 
--------------------
-- exec_bt ---------
/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
-- exec_bt ---------
/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/home/csweetin/apps/VSCode/bin:/home/csweetin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin 
-- after exec ------
-- redirfail -------
Minishell >

**Comment by Jauppp** [comment]
fixed by modifying how input was updated after handle_bt_nopipe
fixed by allowing program to fork for every pipe regargless of content
